### ISSUE TITLE
 ERROR: cannot launch node of type [industrial_robot_client/robot_state]: industrial_robot_client 

### ISSUE THREAD

**Issue by AshwathamanGovind** [ros-industrial/staubli#36]
hai, 
I am trying connect the my tx2_60 robot (cs9 controller) with ROS. Initially i have created a move_it package from tx2_60 using staubli_tx2_60_support and i also have created a custom launch file for planning and execution (PFA). Even though my ros_server is up and running seamlessly in CS9(SP2) i am not able to connect to my robot. I get the following error message saying :- 

ERROR: cannot launch node of type [industrial_robot_client/robot_state]: industrial_robot_client
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/ash/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share
ERROR: cannot launch node of type [industrial_robot_client/motion_streaming_interface]: industrial_robot_client
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/ash/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share
ERROR: cannot launch node of type [industrial_robot_client/joint_trajectory_action]: industrial_robot_client
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/ash/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share

I will also attach the .launch file that i have made for planning and execution

[launch_fileindocs.txt](https://github.com/ros-industrial/staubli/files/6637406/launch_fileindocs.txt)

Can anyone suggest anyway to sort this out??

Thanks in advance

**Comment by gavanderhoorn** [comment]
How did you install everything?

From the error message I see two possibilities:

 1. you only `git clone`d the Staubli related repositories, but did not install any of the dependencies, or
 2. you forgot to source your workspace before trying to start your `.launch` file

re 1) all ROS packages have dependencies. You must install those, or things won't work. See [How to build a package from source on Ubuntu MATE 16.04 LTS and ROS Kinetic?](https://answers.ros.org/question/252478) on ROS Answers for an example of the workflow (it has Kinetic and Ubuntu 16.04 in the title, but it's the same workflow for all ROS versions).

**Comment by gavanderhoorn** [comment]
As this is most likely not an issue with any of the packages here (nor with `staubli_val3_driver`), I'm going to already close it.

If it turns out there is something to fix here, we can re-open.

In all cases, feel free to keep commenting on the issue of course.

**Comment by AshwathamanGovind** [comment]
hey @gavanderhoorn . Thanks for the response. I have sorted out some errors by installing the dependencies. But still, a few are still remaining. I am not sure why i keep getting this error **Action client not connected: manipulator_controller/follow_joint_trajectory**
Even after i have checked all my dependencies and set proper values in my launch file dependencies. 
Any idea on why this is happening?? 

To get an elaborate picture on the issues that i am facing, please have a look at my logs given below:

> auto-starting new master
> process[master]: started with pid [15966]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to e4d550a6-cad7-11eb-8816-30e17123b662
> process[rosout-1]: started with pid [15979]
> started core service [/rosout]
> process[robot_state_publisher-2]: started with pid [15996]
> process[move_group-3]: started with pid [15997]
> process[rviz_ash_HP_ENVY_x360_Convertible_15953_4670776025175027809-4]: started with pid [15998]
> ERROR: cannot launch node of type [warehouse_ros_mongo/mongo_wrapper_ros.py]: warehouse_ros_mongo
> ROS path [0]=/opt/ros/kinetic/share/ros
> ROS path [1]=/home/ash/catkin_ws/src
> ROS path [2]=/opt/ros/kinetic/share
> [ INFO] [1623431418.106461203]: Loading robot model 'staubli_tx2_60'...
> [ INFO] [1623431418.160390030]: rviz version 1.12.17
> [ INFO] [1623431418.160429537]: compiled against Qt version 5.5.1
> [ INFO] [1623431418.160440151]: compiled against OGRE version 1.9.0 (Ghadamon)
> [ INFO] [1623431418.173534110]: Loading robot model 'staubli_tx2_60'...
> [ INFO] [1623431418.226912020]: Publishing maintained planning scene on 'monitored_planning_scene'
> [ INFO] [1623431418.231698717]: MoveGroup debug mode is OFF
> Starting context monitors...
> [ INFO] [1623431418.231804825]: Starting scene monitor
> [ INFO] [1623431418.238828971]: Listening to '/planning_scene'
> [ INFO] [1623431418.238862642]: Starting world geometry monitor
> [ INFO] [1623431418.241512039]: Listening to '/collision_object' using message notifier with target frame '/base_link '
> [ INFO] [1623431418.244205932]: Listening to '/planning_scene_world' for planning scene world geometry
> [ERROR] [1623431418.245818286]: No sensor plugin specified for octomap updater 0; ignoring.
> [ INFO] [1623431418.253779828]: Listening to '/attached_collision_object' for attached collision objects
> Context monitors started.
> [ INFO] [1623431418.288245303]: Initializing OMPL interface using ROS parameters
> [ERROR] [1623431418.292063163]: Could not find the planner configuration 'None' on the param server
> [ INFO] [1623431418.324382687]: Stereo is NOT SUPPORTED
> [ INFO] [1623431418.324478398]: OpenGl version: 3 (GLSL 1.3).
> [ INFO] [1623431418.329060246]: Using planning interface 'OMPL'
> [ INFO] [1623431418.333869688]: Param 'default_workspace_bounds' was not set. Using default value: 10
> [ INFO] [1623431418.334587679]: Param 'start_state_max_bounds_error' was set to 0.1
> [ INFO] [1623431418.335185260]: Param 'start_state_max_dt' was not set. Using default value: 0.5
> [ INFO] [1623431418.335859600]: Param 'start_state_max_dt' was not set. Using default value: 0.5
> [ INFO] [1623431418.336519267]: Param 'jiggle_fraction' was set to 0.05
> [ INFO] [1623431418.338005369]: Param 'max_sampling_attempts' was not set. Using default value: 100
> [ INFO] [1623431418.338086192]: Using planning request adapter 'Add Time Parameterization'
> [ INFO] [1623431418.338104557]: Using planning request adapter 'Fix Workspace Bounds'
> [ INFO] [1623431418.338122353]: Using planning request adapter 'Fix Start State Bounds'
> [ INFO] [1623431418.338139642]: Using planning request adapter 'Fix Start State In Collision'
> [ INFO] [1623431418.338158000]: Using planning request adapter 'Fix Start State Path Constraints'
> [ INFO] [1623431421.738109943]: Loading robot model 'staubli_tx2_60'...
> [ INFO] [1623431421.783820499]: Loading robot model 'staubli_tx2_60'...
> [ INFO] [1623431421.867206435]: Starting scene monitor
> [ INFO] [1623431421.870540942]: Listening to '/move_group/monitored_planning_scene'
> [ INFO] [1623431421.871382825]: waitForService: Service [/get_planning_scene] has not been advertised, waiting...
> [ WARN] [1623431423.369822859]: Waiting for manipulator_controller/follow_joint_trajectory to come up
> [ INFO] [1623431426.887985183]: Failed to call service get_planning_scene, have you launched move_group? at /tmp/binarydeb/ros-kinetic-moveit-ros-planning-0.9.18/planning_scene_monitor/src/planning_scene_monitor.cpp:491
> [ INFO] [1623431427.014931544]: Constructing new MoveGroup connection for group 'manipulator' in namespace ''
> [ WARN] [1623431429.370183138]: Waiting for manipulator_controller/follow_joint_trajectory to come up
> [ERROR] [1623431435.370518687]: Action client not connected: manipulator_controller/follow_joint_trajectory
> [ INFO] [1623431435.408182749]: Returned 0 controllers in list
> [ INFO] [1623431435.441158733]: Trajectory execution is managing controllers
> Loading 'move_group/ApplyPlanningSceneService'...
> Loading 'move_group/ClearOctomapService'...
> Loading 'move_group/MoveGroupCartesianPathService'...
> Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
> Loading 'move_group/MoveGroupGetPlanningSceneService'...
> Loading 'move_group/MoveGroupKinematicsService'...
> Loading 'move_group/MoveGroupMoveAction'...
> Loading 'move_group/MoveGroupPickPlaceAction'...
> Loading 'move_group/MoveGroupPlanService'...
> Loading 'move_group/MoveGroupQueryPlannersService'...
> Loading 'move_group/MoveGroupStateValidationService'...
> [ INFO] [1623431435.518185175]: 
> 
> ********************************************************
>  MoveGroup using: 
>      - ApplyPlanningSceneService
>      - ClearOctomapService
>      - CartesianPathService
>      - ExecuteTrajectoryAction
>      - GetPlanningSceneService
>      - KinematicsService
>      - MoveAction
>      - PickPlaceAction
>     - MotionPlanService
>     - QueryPlannersService
>      - StateValidationService
> ********************************************************
> 
> [ INFO] [1623431435.518239927]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
> [ INFO] [1623431435.518260693]: MoveGroup context initialization complete
> 
> You can start planning now!
> 
>

**Comment by gavanderhoorn** [comment]
Yes, see [How to use staubli_val3_driver/ industrial_robot_simulator with industrial_robot_client and Moveit](https://answers.ros.org/question/379403) on ROS Answers.
