### ISSUE TITLE
Are there efforts for a ros2 port?

### ISSUE THREAD

**Issue by MarioSpeckert** [ros-industrial/staubli#37]
Hi, is there any known effort to port this and the staubli_experimental package to ros2?

**Comment by gavanderhoorn** [comment]
Not at this time.

Note that for `staubli_val3_driver` to be ported, `industrial_core` must be ported.

**Comment by gavanderhoorn** [comment]
I noticed https://github.com/MarioSpeckert/staubli/pull/1.

You might want to consider *not* porting the IKFast plugins: `opw_kinematics` probably makes more sense as an IK solver for 6dof industrial robots.

**Comment by MarioSpeckert** [comment]
Thanks for your reply and the hints on which components have to be ported.
It seems to be a huge endeavor to port all the dependencies to ros2. We most likely stick to ros1 until we have a fully working system and try the port later.

**Comment by gavanderhoorn** [comment]
> It seems to be a huge endeavor to port all the dependencies to ros2

which dependencies are you referring to here?

**Comment by MarioSpeckert** [comment]
To be honest I have not been digging too much into all the dependencies which need a port but from my first impression, especially from the industrial_port package, this is not done in a few hours, at least for me :)
I'm not very experienced with ros2 and starting from a solid foundation with ros1 might be a better plan for now.
